'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clientes
    Public Property CodigoCliente As Integer
    Public Property NIT As String
    Public Property DPI As String
    Public Property Nombre As String

    Public Overridable Property DireccionClientes As ICollection(Of DireccionClientes) = New HashSet(Of DireccionClientes)
    Public Overridable Property EmailClientes As ICollection(Of EmailClientes) = New HashSet(Of EmailClientes)
    Public Overridable Property Facturas As ICollection(Of Facturas) = New HashSet(Of Facturas)
    Public Overridable Property TelefonoClientes As ICollection(Of TelefonoClientes) = New HashSet(Of TelefonoClientes)

End Class
