'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Compras
    Public Property NumeroDocumento As Integer
    Public Property Fecha As Nullable(Of Date)
    Public Property CodigoProveedor As Nullable(Of Integer)
    Public Property TotalCompra As Nullable(Of Decimal)

    Public Overridable Property Proveedores As Proveedores
    Public Overridable Property DetalleCompra As ICollection(Of DetalleCompra) = New HashSet(Of DetalleCompra)

End Class
