'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetalleFactura
    Public Property CodigoFacturaDetalle As Integer
    Public Property CodigoFactura As Integer
    Public Property CodigoProducto As Nullable(Of Integer)
    Public Property Precio As Nullable(Of Decimal)
    Public Property Cantidad As Nullable(Of Integer)
    Public Property SubTotal As Nullable(Of Decimal)

    Public Overridable Property Facturas As Facturas
    Public Overridable Property Productos As Productos

End Class
