'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Facturas
    Public Property CodigoFactura As Integer
    Public Property NumeroFactura As Integer
    Public Property Serie As String
    Public Property FechaFactura As Nullable(Of Date)
    Public Property CodigoCliente As Nullable(Of Integer)
    Public Property Total As Nullable(Of Decimal)

    Public Overridable Property Clientes As Clientes
    Public Overridable Property DetalleFactura As ICollection(Of DetalleFactura) = New HashSet(Of DetalleFactura)

End Class
