'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Inventarios
    Public Property Correlativo As Integer
    Public Property CodigoTipoRegistro As Nullable(Of Integer)
    Public Property Salidas As Nullable(Of Integer)
    Public Property Entradas As Nullable(Of Integer)
    Public Property CodigoProducto As Nullable(Of Integer)
    Public Property Precio As Nullable(Of Decimal)
    Public Property Fecha As Nullable(Of Date)

    Public Overridable Property Productos As Productos
    Public Overridable Property TipoRegistros As TipoRegistros

End Class
