'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailProveedor
    Public Property CodigoEmail As Integer
    Public Property Email As String
    Public Property Descripcion As String
    Public Property CodigoProveedor As Nullable(Of Integer)

    Public Overridable Property Proveedores As Proveedores

End Class
