'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Productos
    Public Property CodigoProducto As Integer
    Public Property Descripcion As String
    Public Property PrecioUnitario As Nullable(Of Decimal)
    Public Property PrecioDocena As Nullable(Of Decimal)
    Public Property PrecioMayor As Nullable(Of Decimal)
    Public Property Existencia As Nullable(Of Integer)
    Public Property Imagen As String
    Public Property CodigoCategoria As Integer
    Public Property CodigoTipoEmpaque As Integer

    Public Overridable Property Categorias As Categorias
    Public Overridable Property DetalleCompra As ICollection(Of DetalleCompra) = New HashSet(Of DetalleCompra)
    Public Overridable Property DetalleFactura As ICollection(Of DetalleFactura) = New HashSet(Of DetalleFactura)
    Public Overridable Property Inventarios As ICollection(Of Inventarios) = New HashSet(Of Inventarios)
    Public Overridable Property TipoEmpaques As TipoEmpaques

End Class
