'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Proveedores
    Public Property CodigoProveedor As Integer
    Public Property NIT As String
    Public Property RazonSocial As String
    Public Property PaginaWeb As String
    Public Property ContactoPrincipal As String

    Public Overridable Property Compras As ICollection(Of Compras) = New HashSet(Of Compras)
    Public Overridable Property DireccionProveedor As ICollection(Of DireccionProveedor) = New HashSet(Of DireccionProveedor)
    Public Overridable Property EmailProveedor As ICollection(Of EmailProveedor) = New HashSet(Of EmailProveedor)
    Public Overridable Property TelefonoProveedor As ICollection(Of TelefonoProveedor) = New HashSet(Of TelefonoProveedor)

End Class
