'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TelefonoClientes
    Public Property CodigoTelefono As Integer
    Public Property NumeroTelefono As String
    Public Property Descripcion As String
    Public Property CodigoCliente As Nullable(Of Integer)

    Public Overridable Property Clientes As Clientes

End Class
